// Comprehensive Bike Database
const bikesData = [
    // Honda Bikes
    {
        id: 1,
        brand: "Honda",
        name: "CBR650R",
        category: "sport",
        price: 895000,
        image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop",
        engine: "649cc",
        power: "95 HP",
        mileage: "22 km/l",
        topSpeed: "200 km/h",
        weight: "211 kg",
        fuelCapacity: "15.4 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "64 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "The CBR650R is a middleweight supersport motorcycle that offers thrilling performance with everyday practicality.",
        features: ["LED Headlights", "Digital Instrument Cluster", "Dual Channel ABS", "Slipper Clutch", "USD Forks"],
        colors: ["Grand Prix Red", "Matte Gunpowder Black Metallic"],
        popular: true
    },
    {
        id: 2,
        brand: "Honda",
        name: "CB350RS",
        category: "cruiser",
        price: 210000,
        image: "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format&fit=crop",
        engine: "348cc",
        power: "20.8 HP",
        mileage: "38 km/l",
        topSpeed: "115 km/h",
        weight: "181 kg",
        fuelCapacity: "15 L",
        brakes: "Dual Channel ABS",
        transmission: "5-Speed",
        torque: "30 Nm",
        cooling: "Air Cooled",
        starter: "Electric & Kick",
        description: "Classic retro styling meets modern technology in this scrambler-inspired roadster.",
        features: ["LED Lighting", "Digital-Analog Meter", "USB Charger", "Assist & Slipper Clutch"],
        colors: ["Rebel Red", "Black with Orange Stripe", "Anniversary Edition"],
        popular: true
    },
    {
        id: 3,
        brand: "Honda",
        name: "Shine 100",
        category: "commuter",
        price: 67000,
        image: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&auto=format&fit=crop",
        engine: "98.98cc",
        power: "7.28 HP",
        mileage: "55 km/l",
        topSpeed: "85 km/h",
        weight: "99 kg",
        fuelCapacity: "9 L",
        brakes: "Drum",
        transmission: "4-Speed",
        torque: "8.05 Nm",
        cooling: "Air Cooled",
        starter: "Self & Kick",
        description: "Affordable and efficient commuter bike perfect for daily city rides.",
        features: ["LED Headlamp", "Tubeless Tyres", "Long Seat", "Mobile Charging"],
        colors: ["Athletic Blue Metallic", "Imperial Red Metallic", "Black"],
        popular: false
    },
    {
        id: 4,
        brand: "Honda",
        name: "Hornet 2.0",
        category: "sport",
        price: 143000,
        image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop",
        engine: "184.4cc",
        power: "17.26 HP",
        mileage: "45 km/l",
        topSpeed: "125 km/h",
        weight: "142 kg",
        fuelCapacity: "12 L",
        brakes: "Single Channel ABS",
        transmission: "5-Speed",
        torque: "16.1 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Aggressive styling and punchy performance make this a street fighter favorite.",
        features: ["Full LED Setup", "Bluetooth Connectivity", "Voice Control", "USB Charger"],
        colors: ["Sports Red", "Matte Axis Gray Metallic", "Matte Marvel Blue Metallic"],
        popular: true
    },
    {
        id: 5,
        brand: "Honda",
        name: "Africa Twin",
        category: "adventure",
        price: 1625000,
        image: "https://images.unsplash.com/photo-1591069690073-871cfde70c9d?w=800&auto=format&fit=crop",
        engine: "1084cc",
        power: "101 HP",
        mileage: "20 km/l",
        topSpeed: "190 km/h",
        weight: "238 kg",
        fuelCapacity: "24.8 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed DCT",
        torque: "105 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Adventure tourer built for conquering any terrain with advanced electronics.",
        features: ["TFT Display", "Riding Modes", "Traction Control", "Cornering ABS", "DCT Option"],
        colors: ["Grand Prix Red", "Matt Ballistic Black Metallic"],
        popular: false
    },

    // Yamaha Bikes
    {
        id: 6,
        brand: "Yamaha",
        name: "R15 V4",
        category: "sport",
        price: 178000,
        image: "https://images.unsplash.com/photo-1598808503491-9446a4740f1e?w=800&auto=format&fit=crop",
        engine: "155cc",
        power: "18.4 HP",
        mileage: "40 km/l",
        topSpeed: "136 km/h",
        weight: "142 kg",
        fuelCapacity: "11 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "14.2 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Track-inspired design with VVA technology for an exhilarating ride.",
        features: ["LED Headlights", "Quickshifter", "Traction Control", "Slipper Clutch", "USD Forks"],
        colors: ["Racing Blue", "Dark Knight", "Metallic Red"],
        popular: true
    },
    {
        id: 7,
        brand: "Yamaha",
        name: "MT-15 V2",
        category: "sport",
        price: 163000,
        image: "https://images.unsplash.com/photo-1558980664-1db506751b82?w=800&auto=format&fit=crop",
        engine: "155cc",
        power: "18.4 HP",
        mileage: "48 km/l",
        topSpeed: "131 km/h",
        weight: "141 kg",
        fuelCapacity: "10 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "14.2 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Naked street fighter with aggressive styling and torquey engine.",
        features: ["LED Lighting", "Digital Console", "VVA Technology", "Slipper Clutch"],
        colors: ["Cyan Storm", "Metallic Black", "Ice Fluo Vermillion"],
        popular: true
    },
    {
        id: 8,
        brand: "Yamaha",
        name: "FZ-X",
        category: "adventure",
        price: 125000,
        image: "https://images.unsplash.com/photo-1558980664-3a031cf67ea8?w=800&auto=format&fit=crop",
        engine: "149cc",
        power: "12.2 HP",
        mileage: "50 km/l",
        topSpeed: "110 km/h",
        weight: "139 kg",
        fuelCapacity: "10 L",
        brakes: "Single Channel ABS",
        transmission: "5-Speed",
        torque: "13.3 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Neo-retro design with adventure styling for urban explorers.",
        features: ["LED Headlight", "Knuckle Guards", "Bluetooth Connectivity", "USB Charging"],
        colors: ["Matte Copper", "Metallic Black", "Travelling Blue"],
        popular: false
    },
    {
        id: 9,
        brand: "Yamaha",
        name: "Aerox 155",
        category: "scooter",
        price: 145000,
        image: "https://images.unsplash.com/photo-1611123935832-317096a5f33c?w=800&auto=format&fit=crop",
        engine: "155cc",
        power: "15.4 HP",
        mileage: "42 km/l",
        topSpeed: "120 km/h",
        weight: "126 kg",
        fuelCapacity: "5.5 L",
        brakes: "Dual Channel ABS",
        transmission: "CVT",
        torque: "13.9 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Sporty maxi-scooter with premium features and dynamic performance.",
        features: ["LED Lighting", "Smart Key", "TFT Display", "Traction Control", "Side Stand Engine Cut-off"],
        colors: ["Racing Blue", "Matte Black", "Turbo Red"],
        popular: true
    },
    {
        id: 10,
        brand: "Yamaha",
        name: "Ray ZR 125",
        category: "scooter",
        price: 85000,
        image: "https://images.unsplash.com/photo-1611123935832-317096a5f33c?w=800&auto=format&fit=crop",
        engine: "125cc",
        power: "8.2 HP",
        mileage: "58 km/l",
        topSpeed: "90 km/h",
        weight: "99 kg",
        fuelCapacity: "5.2 L",
        brakes: "Drum",
        transmission: "CVT",
        torque: "10.3 Nm",
        cooling: "Air Cooled",
        starter: "Electric & Kick",
        description: "Stylish and practical scooter with comfortable ride quality.",
        features: ["LED Headlight", "Digital Meter", "Side Stand Switch", "Mobile Charging"],
        colors: ["Cyan Blue", "Metallic Black", "Red"],
        popular: false
    },

    // Royal Enfield Bikes
    {
        id: 11,
        brand: "Royal Enfield",
        name: "Hunter 350",
        category: "cruiser",
        price: 165000,
        image: "https://images.unsplash.com/photo-1558980664-10e7170b5df9?w=800&auto=format&fit=crop",
        engine: "349cc",
        power: "20.2 HP",
        mileage: "36 km/l",
        topSpeed: "114 km/h",
        weight: "181 kg",
        fuelCapacity: "13 L",
        brakes: "Dual Channel ABS",
        transmission: "5-Speed",
        torque: "27 Nm",
        cooling: "Air-Oil Cooled",
        starter: "Electric",
        description: "Urban roadster with retro charm and modern capability.",
        features:["LED Tail Light", "Tripper Navigation", "USB Charging", "Counter Balancer"],
        colors: ["Rebel Red", "Dapper Ash", "Metro Dapper"],
        popular: true
    },
    {
        id: 12,
        brand: "Royal Enfield",
        name: "Classic 350",
        category: "cruiser",
        price: 195000,
        image: "https://images.unsplash.com/photo-1558980664-1c406f7d6a0c?w=800&auto=format&fit=crop",
        engine: "349cc",
        power: "20.2 HP",
        mileage: "35 km/l",
        topSpeed: "110 km/h",
        weight: "195 kg",
        fuelCapacity: "13 L",
        brakes: "Dual Channel ABS",
        transmission: "5-Speed",
        torque: "27 Nm",
        cooling: "Air-Oil Cooled",
        starter: "Electric",
        description: "Timeless classic design with legendary Royal Enfield heritage.",
        features:["Semi-Digital Cluster", "Tripper Navigation Ready", "Tubeless Tyres", "Dual Channel ABS"],
        colors:["Signals", "Dark", "Halcyon", "Chrome"],
        popular: true
    },
    {
        id: 13,
        brand: "Royal Enfield",
        name: "Himalayan",
        category: "adventure",
        price: 235000,
        image: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&auto=format&fit=crop",
        engine: "411cc",
        power: "24.3 HP",
        mileage: "30 km/l",
        topSpeed: "120 km/h",
        weight: "199 kg",
        fuelCapacity: "15 L",
        brakes: "Dual Channel ABS",
        transmission: "5-Speed",
        torque: "32 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Purpose-built adventure motorcycle for all terrains.",
        features: ["Digital Compass", "Tripper Navigation", "Long Travel Suspension", "Switchable ABS"],
        colors: ["Granite Black", "Mirage Silver", "Rock Red"],
        popular: true
    },
    {
        id: 14,
        brand: "Royal Enfield",
        name: "Interceptor 650",
        category: "cruiser",
        price: 310000,
        image: "https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800&auto=format&fit=crop",
        engine: "648cc",
        power: "47 HP",
        mileage: "25 km/l",
        topSpeed: "160 km/h",
        weight: "202 kg",
        fuelCapacity: "12.5 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "52 Nm",
        cooling: "Oil Cooled",
        starter: "Electric",
        description: "Parallel-twin engine delivering smooth power and retro appeal.",
        features: ["Twin Exhaust", "Analog Instruments", "Dual Channel ABS", "Slipper Clutch"],
        colors: ["Baker Express", "Downtown Drag", "Sunset Strip", "Ravishing Red"],
        popular: true
    },
    {
        id: 15,
        brand: "Royal Enfield",
        name: "Meteor 350",
        category: "cruiser",
        price: 210000,
        image: "https://images.unsplash.com/photo-1558980664-10e7170b5df9?w=800&auto=format&fit=crop",
        engine: "349cc",
        power: "20.2 HP",
        mileage: "36 km/l",
        topSpeed: "115 km/h",
        weight: "191 kg",
        fuelCapacity: "15 L",
        brakes: "Dual Channel ABS",
        transmission: "5-Speed",
        torque: "27 Nm",
        cooling: "Air-Oil Cooled",
        starter: "Electric",
        description: "Easy cruising with comfortable ergonomics for long rides.",
        features:["Tripper Navigation", "LED Tail Light", "USB Charging", "Hazard Lights"],
        colors: ["Fireball", "Stellar", "Supernova"],
        popular: false
    },

    // KTM Bikes
    {
        id: 16,
        brand: "KTM",
        name: "RC 390",
        category: "sport",
        price: 315000,
        image: "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format&fit=crop",
        engine: "373.2cc",
        power: "43.5 HP",
        mileage: "30 km/l",
        topSpeed: "167 km/h",
        weight: "172 kg",
        fuelCapacity: "13.7 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "37 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Track-focused supersport with race-bred DNA.",
        features: ["TFT Display", "Ride by Wire", "Quickshifter+", "Supermoto ABS", "LED Headlights"],
        colors: ["RC Cup", "White"],
        popular: true
    },
    {
        id: 17,
        brand: "KTM",
        name: "Duke 390",
        category: "sport",
        price: 298000,
        image: "https://images.unsplash.com/photo-1558980664-1c406f7d6a0c?w=800&auto=format&fit=crop",
        engine: "373.2cc",
        power: "43.5 HP",
        mileage: "32 km/l",
        topSpeed: "167 km/h",
        weight: "167 kg",
        fuelCapacity: "13.4 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "37 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "The scalpel sharp naked bike with unmatched agility.",
        features: ["TFT Display", "Connectivity", "Quickshifter+", "Cornering ABS", "Traction Control"],
        colors: ["Dark Galvano", "Electric Orange"],
        popular: true
    },
    {
        id: 18,
        brand: "KTM",
        name: "Duke 250",
        category: "sport",
        price: 235000,
        image: "https://images.unsplash.com/photo-1558980664-3a031cf67ea8?w=800&auto=format&fit=crop",
        engine: "248.8cc",
        power: "30 HP",
        mileage: "35 km/l",
        topSpeed: "140 km/h",
        weight: "159 kg",
        fuelCapacity: "13.4 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "24 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Lightweight naked bike with sharp handling characteristics.",
        features: ["LCD Display", "LED Lighting", "WP Suspension", "Dual Channel ABS"],
        colors: ["Dark Galvano", "White"],
        popular: false
    },
    {
        id: 19,
        brand: "KTM",
        name: "Adventure 390",
        category: "adventure",
        price: 355000,
        image: "https://images.unsplash.com/photo-1591069690073-871cfde70c9d?w=800&auto=format&fit=crop",
        engine: "373.2cc",
        power: "43.5 HP",
        mileage: "28 km/l",
        topSpeed: "160 km/h",
        weight: "177 kg",
        fuelCapacity: "14.5 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "37 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Adventure bike ready to explore any terrain.",
        features: ["TFT Display", "Cornering ABS", "Off-Road ABS", "Traction Control", "Quickshifter+"],
        colors: ["Orange", "White"],
        popular: true
    },
    {
        id: 20,
        brand: "KTM",
        name: "Duke 125",
        category: "sport",
        price: 185000,
        image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format&fit=crop",
        engine: "124.7cc",
        power: "14.5 HP",
        mileage: "40 km/l",
        topSpeed: "120 km/h",
        weight: "147 kg",
        fuelCapacity: "10.2 L",
        brakes: "Single Channel ABS",
        transmission: "6-Speed",
        torque: "12 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Entry-level street fighter with premium features.",
        features: ["LCD Display", "LED Lighting", "WP Suspension", "Single Channel ABS"],
        colors: ["Dark Galvano", "Orange"],
        popular: false
    },

    // Bajaj Bikes
    {
        id: 21,
        brand: "Bajaj",
        name: "Pulsar NS200",
        category: "sport",
        price: 145000,
        image: "https://images.unsplash.com/photo-1598808503491-9446a4740f1e?w=800&auto=format&fit=crop",
        engine: "199.5cc",
        power: "24.5 HP",
        mileage: "40 km/l",
        topSpeed: "135 km/h",
        weight: "152 kg",
        fuelCapacity: "12 L",
        brakes: "Single Channel ABS",
        transmission: "6-Speed",
        torque: "18.5 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Naked sports bike with perimeter frame and dynamic performance.",
        features: ["LED DRL", "Digital Console", "Perimeter Frame", "Single Channel ABS"],
        colors: ["Burnt Red", "Fiery Yellow", "Metallic Pearl White"],
        popular: true
    },
    {
        id: 22,
        brand: "Bajaj",
        name: "Dominar 400",
        category: "cruiser",
        price: 225000,
        image: "https://images.unsplash.com/photo-1558980664-1db506751b82?w=800&auto=format&fit=crop",
        engine: "373.3cc",
        power: "40 HP",
        mileage: "30 km/l",
        topSpeed: "156 km/h",
        weight: "193 kg",
        fuelCapacity: "13 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "35 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Highway cruiser with touring capabilities and strong performance.",
        features: ["LED Lighting", "USD Forks", "Dual Channel ABS", "Slipper Clutch"],
        colors: ["Aurora Green", "Vine Black", "Canyon Red"],
        popular: true
    },
    {
        id: 23,
        brand: "Bajaj",
        name: "Pulsar 150",
        category: "commuter",
        price: 110000,
        image: "https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800&auto=format&fit=crop",
        engine: "149.5cc",
        power: "14 HP",
        mileage: "50 km/l",
        topSpeed: "115 km/h",
        weight: "144 kg",
        fuelCapacity: "15 L",
        brakes: "Drum",
        transmission: "5-Speed",
        torque: "13.25 Nm",
        cooling: "Air Cooled",
        starter: "Electric & Kick",
        description: "Popular commuter motorcycle with sporty styling.",
        features: ["LED Tail Light", "Split Seat", "Tubeless Tyres", "Electric Start"],
        colors: ["Caribbean Blue", "Ebony Black", "Laser Black Red"],
        popular: true
    },
    {
        id: 24,
        brand: "Bajaj",
        name: "Avenger 220 Cruise",
        category: "cruiser",
        price: 140000,
        image: "https://images.unsplash.com/photo-1558980664-10e7170b5df9?w=800&auto=format&fit=crop",
        engine: "220cc",
        power: "19 HP",
        mileage: "40 km/l",
        topSpeed: "110 km/h",
        weight: "152 kg",
        fuelCapacity: "13 L",
        brakes: "Disc",
        transmission: "5-Speed",
        torque: "17.5 Nm",
        cooling: "Oil Cooled",
        starter: "Electric",
        description: "Affordable cruiser with comfortable riding position.",
        features: ["Digital Console", "LED DRL", "USB Charger", "Backrest"],
        colors: ["Ebony Black Blue", "Spicy Red"],
        popular: false
    },
    {
        id: 25,
        brand: "Bajaj",
        name: "CT 110X",
        category: "commuter",
        price: 60000,
        image: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&auto=format&fit=crop",
        engine: "115cc",
        power: "8.6 HP",
        mileage: "70 km/l",
        topSpeed: "90 km/h",
        weight: "117 kg",
        fuelCapacity: "10.5 L",
        brakes: "Drum",
        transmission: "4-Speed",
        torque: "9.81 Nm",
        cooling: "Air Cooled",
        starter: "Kick",
        description: "Rugged and fuel-efficient bike for rural areas.",
        features: ["Spoke Wheels", "Long Seat", "Grab Rail", "LED Tail Light"],
        colors: ["Ebony Black with Blue Decals", "Ebony Black with Red Decals"],
        popular: false
    },

    // TVS Bikes
    {
        id: 26,
        brand: "TVS",
        name: "Apache RR 310",
        category: "sport",
        price: 270000,
        image: "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format&fit=crop",
        engine: "312.2cc",
        power: "34 HP",
        mileage: "32 km/l",
        topSpeed: "160 km/h",
        weight: "174 kg",
        fuelCapacity: "11 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "27.3 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Full-faired sportbike with sharp handling and aerodynamic design.",
        features:["LED Headlights", "TFT Display", "Ride Modes", "Dual Channel ABS", "Slipper Clutch"],
        colors: ["Dynamic Red Gloss", "Phantom Black Gloss", "Apache White Gloss"],
        popular: true
    },
    {
        id: 27,
        brand: "TVS",
        name: "Apache RTR 160 4V",
        category: "sport",
        price: 125000,
        image: "https://images.unsplash.com/photo-1598808503491-9446a4740f1e?w=800&auto=format&fit=crop",
        engine: "159.7cc",
        power: "17.63 HP",
        mileage: "45 km/l",
        topSpeed: "117 km/h",
        weight: "147 kg",
        fuelCapacity: "12 L",
        brakes: "Single Channel ABS",
        transmission: "5-Speed",
        torque: "14.73 Nm",
        cooling: "Oil Cooled",
        starter: "Electric",
        description: "Sporty commuter with race-derived technology.",
        features:["LED DRL", "SmartXonnect", "GTT", "Race Tuned Fuel Injection"],
        colors: ["Metallic Red", "Pearl White", "Knight Black"],
        popular: true
    },
    {
        id: 28,
        brand: "TVS",
        name: "Ronin",
        category: "cruiser",
        price: 155000,
        image: "https://images.unsplash.com/photo-1558980664-1c406f7d6a0c?w=800&auto=format&fit=crop",
        engine: "225.9cc",
        power: "20.4 HP",
        mileage: "40 km/l",
        topSpeed: "120 km/h",
        weight: "159 kg",
        fuelCapacity: "14 L",
        brakes: "Dual Channel ABS",
        transmission: "5-Speed",
        torque: "19.93 Nm",
        cooling: "Oil Cooled",
        starter: "Electric",
        description: "Scrambler with retro-modern design and customization options.",
        features: ["LED Lighting", "TFT Display", "Bluetooth Connectivity", "Navigation", "USB Charging"],
        colors: ["Stargaze Black", "Wicked Black", "Titanium Grey"],
        popular: false
    },
    {
        id: 29,
        brand: "TVS",
        name: "Jupiter 125",
        category: "scooter",
        price: 88000,
        image: "https://images.unsplash.com/photo-1611123935832-317096a5f33c?w=800&auto=format&fit=crop",
        engine: "124.8cc",
        power: "8.15 HP",
        mileage: "62 km/l",
        topSpeed: "90 km/h",
        weight: "108 kg",
        fuelCapacity: "6 L",
        brakes: "Drum",
        transmission: "CVT",
        torque: "10.5 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Family scooter with spacious storage and comfortable ride.",
        features: ["LED Headlight", "SmartXonnect", "USB Charger", "External Fuel Filler"],
        colors: ["Stallion Black", "Royal Wine", "Titanium Grey"],
        popular: true
    },
    {
        id: 30,
        brand: "TVS",
        name: "Raider 125",
        category: "commuter",
        price: 95000,
        image: "https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800&auto=format&fit=crop",
        engine: "124.8cc",
        power: "11.38 HP",
        mileage: "67 km/l",
        topSpeed: "99 km/h",
        weight: "123 kg",
        fuelCapacity: "10 L",
        brakes: "Disc",
        transmission: "5-Speed",
        torque: "11.2 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Stylish commuter with segment-first features.",
        features:["LED Headlamp", "SmartXonnect", "Voice Assist", "USB Charger"],
        colors: ["Fiery Yellow", "Striking Red", "Midnight Black"],
        popular: false
    },

    // Suzuki Bikes
    {
        id: 31,
        brand: "Suzuki",
        name: "Gixxer SF 250",
        category: "sport",
        price: 195000,
        image: "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format&fit=crop",
        engine: "249cc",
        power: "26.5 HP",
        mileage: "35 km/l",
        topSpeed: "150 km/h",
        weight: "161 kg",
        fuelCapacity: "12 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "22.6 Nm",
        cooling: "Oil Cooled",
        starter: "Electric",
        description: "Faired sports bike with aggressive styling and performance.",
        features: ["LED Headlamp", "Digital Console", "Dual Channel ABS", "Slipper Clutch"],
        colors: ["Glass Sparkle Black", "Metallic Triton Blue", "Candy Antares Red"],
        popular: true
    },
    {
        id: 32,
        brand: "Suzuki",
        name: "V-Strom SX",
        category: "adventure",
        price: 235000,
        image: "https://images.unsplash.com/photo-1591069690073-871cfde70c9d?w=800&auto=format&fit=crop",
        engine: "249cc",
        power: "26.5 HP",
        mileage: "30 km/l",
        topSpeed: "145 km/h",
        weight: "167 kg",
        fuelCapacity: "12 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "22.2 Nm",
        cooling: "Oil Cooled",
        starter: "Electric",
        description: "Adventure tourer with versatile performance.",
        features: ["LED Lighting", "Digital Console", "USB Charger", "Dual Channel ABS"],
        colors: ["Champion Yellow", "Glass Sparkle Black", "Metallic Mat Black"],
        popular: false
    },
    {
        id: 33,
        brand: "Suzuki",
        name: "Avenis 125",
        category: "scooter",
        price: 92000,
        image: "https://images.unsplash.com/photo-1611123935832-317096a5f33c?w=800&auto=format&fit=crop",
        engine: "124cc",
        power: "8.7 HP",
        mileage: "60 km/l",
        topSpeed: "92 km/h",
        weight: "106 kg",
        fuelCapacity: "5.2 L",
        brakes: "Drum",
        transmission: "CVT",
        torque: "10 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Sporty scooter with premium features and comfort.",
        features: ["LED Headlamp", "Digital Console", "Bluetooth Connectivity", "USB Charger"],
        colors: ["Metallic Matte Black", "Pearl Mirage White", "Distinct Bronze"],
        popular: false
    },
    {
        id: 34,
        brand: "Suzuki",
        name: "Access 125",
        category: "scooter",
        price: 82000,
        image: "https://images.unsplash.com/photo-1611123935832-317096a5f33c?w=800&auto=format&fit=crop",
        engine: "124cc",
        power: "8.7 HP",
        mileage: "64 km/l",
        topSpeed: "90 km/h",
        weight: "104 kg",
        fuelCapacity: "5 L",
        brakes: "Drum",
        transmission: "CVT",
        torque: "10 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Practical scooter with excellent fuel economy.",
        features: ["LED Headlamp", "Digital Console", "USB Charger", "Front Storage"],
        colors: ["Metallic Sonic Silver", "Pearl Mirage White", "Matte Black"],
        popular: true
    },
    {
        id: 35,
        brand: "Suzuki",
        name: "Burgman Street",
        category: "scooter",
        price: 105000,
        image: "https://images.unsplash.com/photo-1611123935832-317096a5f33c?w=800&auto=format&fit=crop",
        engine: "124cc",
        power: "8.7 HP",
        mileage: "58 km/l",
        topSpeed: "92 km/h",
        weight: "108 kg",
        fuelCapacity: "5.6 L",
        brakes: "Disc",
        transmission: "CVT",
        torque: "10 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Maxi-scooter with premium styling and features.",
        features: ["LED Lighting", "Fully Digital Console", "USB Charger", "Smartphone Connectivity"],
        colors: ["Metallic Mat Black", "Glass Sparkle Black", "Pearl Mirage White"],
        popular: false
    },

    // Kawasaki Bikes
    {
        id: 36,
        brand: "Kawasaki",
        name: "Ninja 400",
        category: "sport",
        price: 535000,
        image: "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format&fit=crop",
        engine: "399cc",
        power: "49 HP",
        mileage: "28 km/l",
        topSpeed: "180 km/h",
        weight: "168 kg",
        fuelCapacity: "14 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "38 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Lightweight supersport with impressive power-to-weight ratio.",
        features: ["LED Lighting", "Digital Display", "Slipper Clutch", "Dual Channel ABS"],
        colors: ["Lime Green/Ebony", "Metallic Spark Black"],
        popular: true
    },
    {
        id: 37,
        brand: "Kawasaki",
        name: "Z900",
        category: "sport",
        price: 920000,
        image: "https://images.unsplash.com/photo-1558980664-1c406f7d6a0c?w=800&auto=format&fit=crop",
        engine: "948cc",
        power: "125 HP",
        mileage: "20 km/l",
        topSpeed: "230 km/h",
        weight: "210 kg",
        fuelCapacity: "17 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "98.6 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Aggressive naked bike with superbike-derived engine.",
        features:["TFT Display", "LED Lighting", "Traction Control", "Ride Modes", "Quickshifter"],
        colors:["Metallic Spark Black/Metallic Flat Spark Black", "Candy Lime Green/Ebony"],
        popular: true
    },
    {
        id: 38,
        brand: "Kawasaki",
        name: "Versys 650",
        category: "adventure",
        price: 775000,
        image: "https://images.unsplash.com/photo-1591069690073-871cfde70c9d?w=800&auto=format&fit=crop",
        engine: "649cc",
        power: "69 HP",
        mileage: "22 km/l",
        topSpeed: "185 km/h",
        weight: "216 kg",
        fuelCapacity: "21 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "61 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Versatile adventure tourer for long-distance comfort.",
        features: ["TFT Display", "LED Lighting", "Smartphone Connectivity", "Adjustable Windscreen"],
        colors: ["Metallic Spark Black/Metallic Flat Spark Black", "Pearl Robotic White/Metallic Flat Spark Black"],
        popular: false
    },
    {
        id: 39,
        brand: "Kawasaki",
        name: "Ninja ZX-10R",
        category: "sport",
        price: 1499000,
        image: "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format&fit=crop",
        engine: "998cc",
        power: "203 HP",
        mileage: "15 km/l",
        topSpeed: "299 km/h",
        weight: "207 kg",
        fuelCapacity: "17 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "114.9 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Race-bred superbike with cutting-edge technology.",
        features:["Full Color TFT", "Cornering ABS", "Traction Control", "Quickshifter", "Launch Control"],
        colors: ["Lime Green/Ebony", "Metallic Spark Black/Metallic Flat Spark Black"],
        popular: false
    },
    {
        id: 40,
        brand: "Kawasaki",
        name: "W175",
        category: "cruiser",
        price: 155000,
        image: "https://images.unsplash.com/photo-1558980664-10e7170b5df9?w=800&auto=format&fit=crop",
        engine: "177cc",
        power: "13 HP",
        mileage: "40 km/l",
        topSpeed: "105 km/h",
        weight: "127 kg",
        fuelCapacity: "13 L",
        brakes: "Drum",
        transmission: "5-Speed",
        torque: "13.2 Nm",
        cooling: "Air Cooled",
        starter: "Electric & Kick",
        description: "Retro-styled commuter with classic appeal.",
        features: ["Spoke Wheels", "Analog Meter", "Electric & Kick Start", "Classic Design"],
        colors: ["Ebony/Brown", "Pearl Lava Orange/Metallic Graphite Gray"],
        popular: false
    },

    // Ducati Bikes
    {
        id: 41,
        brand: "Ducati",
        name: "Panigale V4",
        category: "sport",
        price: 2899000,
        image: "https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format&fit=crop",
        engine: "1103cc",
        power: "214 HP",
        mileage: "14 km/l",
        topSpeed: "305 km/h",
        weight: "198 kg",
        fuelCapacity: "16 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "124 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "MotoGP-derived superbike with extreme performance.",
        features: ["TFT Display", "Cornering ABS", "Traction Control", "Wheelie Control", "Launch Control"],
        colors: ["Ducati Red", "Black"],
        popular: true
    },
    {
        id: 42,
        brand: "Ducati",
        name: "Monster",
        category: "sport",
        price: 1199000,
        image: "https://images.unsplash.com/photo-1558980664-1c406f7d6a0c?w=800&auto=format&fit=crop",
        engine: "937cc",
        power: "111 HP",
        mileage: "18 km/l",
        topSpeed: "220 km/h",
        weight: "188 kg",
        fuelCapacity: "14 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "93 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Iconic naked bike with modern performance.",
        features: ["TFT Display", "Riding Modes", "Traction Control", "Cornering ABS", "Quickshifter"],
        colors: ["Ducati Red", "Dark Stealth", "Aviator Grey"],
        popular: true
    },
    {
        id: 43,
        brand: "Ducati",
        name: "Scrambler Icon",
        category: "cruiser",
        price: 899000,
        image: "https://images.unsplash.com/photo-1558980664-10e7170b5df9?w=800&auto=format&fit=crop",
        engine: "803cc",
        power: "73 HP",
        mileage: "22 km/l",
        topSpeed: "180 km/h",
        weight: "189 kg",
        fuelCapacity: "13.5 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "66.2 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Retro scrambler with modern technology.",
        features: ["LCD Display", "LED Lighting", "Cornering ABS", "Traction Control"],
        colors: ["Red Shiny", "Black", "Blue & White"],
        popular: false
    },
    {
        id: 44,
        brand: "Ducati",
        name: "Multistrada V4",
        category: "adventure",
        price: 2599000,
        image: "https://images.unsplash.com/photo-1591069690073-871cfde70c9d?w=800&auto=format&fit=crop",
        engine: "1158cc",
        power: "170 HP",
        mileage: "16 km/l",
        topSpeed: "260 km/h",
        weight: "218 kg",
        fuelCapacity: "22 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "125 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Sport-touring bike with advanced electronics and comfort.",
        features: ["TFT Display", "Radar", "Adaptive Cruise Control", "Riding Modes", "Semi-Active Suspension"],
        colors: ["Ducati Red", "Thrilling Black", "Arctic White Silk"],
        popular: false
    },
    {
        id: 45,
        brand: "Ducati",
        name: "Diavel V4",
        category: "cruiser",
        price: 2599000,
        image: "https://images.unsplash.com/photo-1558980664-1db506751b82?w=800&auto=format&fit=crop",
        engine: "1158cc",
        power: "168 HP",
        mileage: "15 km/l",
        topSpeed: "250 km/h",
        weight: "221 kg",
        fuelCapacity: "17 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "126 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Power cruiser combining muscle and sophistication.",
        features: ["TFT Display", "Riding Modes", "Cornering ABS", "Traction Control", "Launch Control"],
        colors: ["Thrilling Black", "Dark Stealth"],
        popular: false
    },

    // Harley-Davidson Bikes
    {
        id: 46,
        brand: "Harley-Davidson",
        name: "Street 750",
        category: "cruiser",
        price: 545000,
        image: "https://images.unsplash.com/photo-1558980664-10e7170b5df9?w=800&auto=format&fit=crop",
        engine: "749cc",
        power: "60 HP",
        mileage: "20 km/l",
        topSpeed: "160 km/h",
        weight: "233 kg",
        fuelCapacity: "13.1 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "65 Nm",
        cooling: "Liquid Cooled",
        starter: "Electric",
        description: "Urban cruiser with classic Harley styling.",
        features: ["ABS", "Digital Speedometer", "Liquid Cooling", "Mid Controls"],
        colors: ["Vivid Black", "Billiard Gray"],
        popular: true
    },
    {
        id: 47,
        brand: "Harley-Davidson",
        name: "Iron 883",
        category: "cruiser",
        price: 995000,
        image: "https://images.unsplash.com/photo-1558980664-1c406f7d6a0c?w=800&auto=format&fit=crop",
        engine: "883cc",
        power: "70 HP",
        mileage: "18 km/l",
        topSpeed: "175 km/h",
        weight: "256 kg",
        fuelCapacity: "12.5 L",
        brakes: "Dual Channel ABS",
        transmission: "5-Speed",
        torque: "69 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Dark custom with authentic Sportster soul.",
        features: ["ABS", "Electronic Fuel Injection", "Belt Drive", "Chopped Fenders"],
        colors: ["Vivid Black", "Barracuda Silver"],
        popular: true
    },
    {
        id: 48,
        brand: "Harley-Davidson",
        name: "Fat Boy",
        category: "cruiser",
        price: 1995000,
        image: "https://images.unsplash.com/photo-1558980664-1db506751b82?w=800&auto=format&fit=crop",
        engine: "1868cc",
        power: "94 HP",
        mileage: "15 km/l",
        topSpeed: "180 km/h",
        weight: "317 kg",
        fuelCapacity: "18.9 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "155 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Iconic muscle cruiser with massive presence.",
        features: ["ABS", "Cruise Control", "USB Port", "Keyless Ignition", "LED Lighting"],
        colors: ["Vivid Black", "Billiard Blue"],
        popular: false
    },
    {
        id: 49,
        brand: "Harley-Davidson",
        name: "Road Glide",
        category: "cruiser",
        price: 3495000,
        image: "https://images.unsplash.com/photo-1558980664-10e7170b5df9?w=800&auto=format&fit=crop",
        engine: "1868cc",
        power: "94 HP",
        mileage: "16 km/l",
        topSpeed: "185 km/h",
        weight: "362 kg",
        fuelCapacity: "22.7 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "163 Nm",
        cooling: "Air Cooled",
        starter: "Electric",
        description: "Premium touring motorcycle built for long distance.",
        features: ["TFT Display", "Navigation", "Cruise Control", "Heated Grips", "Premium Audio"],
        colors: ["Vivid Black", "Billiard White"],
        popular: false
    },
    {
        id: 50,
        brand: "Harley-Davidson",
        name: "X440",
        category: "cruiser",
        price: 249000,
        image: "https://images.unsplash.com/photo-1558980664-1c406f7d6a0c?w=800&auto=format&fit=crop",
        engine: "440cc",
        power: "27 HP",
        mileage: "35 km/l",
        topSpeed: "145 km/h",
        weight: "221 kg",
        fuelCapacity: "13.5 L",
        brakes: "Dual Channel ABS",
        transmission: "6-Speed",
        torque: "38 Nm",
        cooling: "Oil Cooled",
        starter: "Electric",
        description: "Affordable entry to Harley-Davidson's cruiser lineup.",
        features: ["LED Lighting", "Digital-Analog Meter", "Dual Channel ABS", "USB Charging"],
        colors: ["Vivid Red", "Denim Black", "Metallic Yellow"],
        popular: true
    }
];


